### ISSUE TITLE
Show Group Invite link

### ISSUE THREAD

**Issue by f-breidenstein** [OpenSplit/old-frontend#2]
Print the Invite link somewhere on the Group page

**Comment by mschader** [comment]
Which api endpoint delivers the link?

**Comment by f-breidenstein** [comment]
The token is now part of the general group info which you get from the backend. Take it from the "token" field. The invite link for a group is
```
%BASE_URL + '/group/' + token
```

**Comment by mschader** [comment]
Is shown on the group page. The issue will remain open until the positioning and styling of the link ist finalized.
